[general]
import = [
  "themes/themes/campbell.toml",
  "font/jetBrainsMono.toml"
]

[cursor.style]
shape = "Beam"
blinking = "On"

[terminal]
shell = "nu"
osc52 = "CopyPaste"

[window]
dynamic_padding = false
decorations = "buttonless"
opacity = 0.95
blur = true
dynamic_title = true

[window.dimensions]
columns = 120
lines = 32

[window.padding]
x = 6
y = 6

[bell]
animation = "EaseOutSine"
color = "#ffffff"
duration = 200

[font]
size = 14.0

[env]
ALACRITTY_WIN = "%APPDATA%/alacritty/alacritty.toml"
ALACRITTY_WIN_NU = "$env.APPDATA/alacritty/alacritty.toml"
ALACRITTY_UNIX = "$HOME/.config/alacritty/alacritty.toml"
ALACRITTY_UNIX_NU = "$env.HOME/.config/alacritty/alacritty.toml"