[general]
import = [
  "theme.campbell.toml"
]

[cursor.style]
shape = "Beam"
blinking = "On"

[terminal]
shell = "nu"
osc52 = "CopyPaste"

[window]
dimensions = { columns = 120, lines = 32 }
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "transparent"
opacity = 0.95
blur = true
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono"}
size = 14.0

[env]
ALACRITTY_WIN = "%APPDATA%/alacritty/alacritty.toml"
ALACRITTY_WIN_NU = "$env.APPDATA/alacritty/alacritty.toml"
ALACRITTY_UNIX = "$HOME/.config/alacritty/alacritty.toml"
ALACRITTY_UNIX_NU = "$env.HOME/.config/alacritty/alacritty.toml"