[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"