[colors.primary]
foreground = "#CCCCCC"
background = "#0C0C0C"

[colors.normal]
black = "#0C0C0C"
blue = "#0037DA"
cyan = "#3A96DD"
green = "#13A10E"
magenta = "#881798"
red = "#C50F1F"
white = "#CCCCCC"
yellow = "#C19C00"

[colors.bright]
black = "#767676"
blue = "#3B78FF"
cyan = "#61D6D6"
green = "#16C60C"
magenta = "#B4009E"
red = "#E74856"
white = "#F2F2F2"
yellow = "#F9F1A5"